# Generated by Django 5.0.9 on 2024-11-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowcounter', models.IntegerField(db_column='RowCounter')),
            ],
            options={
                'db_table': 'Counter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('directorid', models.AutoField(db_column='DirectorID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Directors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genreid', models.AutoField(db_column='GenreID', primary_key=True, serialize=False)),
                ('genrename', models.CharField(blank=True, db_column='GenreName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieid', models.AutoField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
                ('releasedate', models.DateField(blank=True, db_column='ReleaseDate', null=True)),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('sessionid', models.AutoField(db_column='SessionID', primary_key=True, serialize=False)),
                ('sessiondatetime', models.DateTimeField(blank=True, db_column='SessionDateTime', null=True)),
                ('availableseats', models.IntegerField(blank=True, db_column='AvailableSeats', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionsCopy',
            fields=[
                ('copyid', models.AutoField(db_column='CopyID', primary_key=True, serialize=False)),
                ('sessionid', models.IntegerField(blank=True, db_column='SessionID', null=True)),
                ('movietitle', models.CharField(blank=True, db_column='MovieTitle', max_length=255, null=True)),
                ('sessiondatetime', models.DateTimeField(blank=True, db_column='SessionDateTime', null=True)),
                ('oldprice', models.DecimalField(blank=True, db_column='OldPrice', decimal_places=2, max_digits=10, null=True)),
                ('newprice', models.DecimalField(blank=True, db_column='NewPrice', decimal_places=2, max_digits=10, null=True)),
                ('changedatetime', models.DateTimeField(blank=True, db_column='ChangeDateTime', null=True)),
            ],
            options={
                'db_table': 'Sessions_Copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticketid', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('discount', models.DecimalField(blank=True, db_column='Discount', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Tickets',
                'managed': False,
            },
        ),
    ]
